project:
  name: cfn-ps-sumo-logic-cloudsiem
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
    - us-east-1
  artifact_regions:
    - us-east-1
tests:
  default:
    template: ./templates/main-org.template.yaml
    regions:
    - us-east-1
    parameters:
      QSS3KeyPrefix: "cfn-ps-sumo-logic-cloudsiem/"
      QSS3BucketName:  "$[taskcat_autobucket_prefix]"
      QSS3BucketRegion: "us-east-1"
      QSVersion: "2"
      Section1SumoLogicDeployment: "us2"
      Section1SumoLogicAccessID: $[taskcat_ssm_/sumologic/Section1SumoLogicAccessID]
      Section1SumoLogicAccessKey: $[taskcat_ssm_/sumologic/Section1SumoLogicAccessKey]
      Section1SumoLogicOrganizationId: $[taskcat_ssm_/sumologic/Section1SumoLogicOrganizationId]
      Section1SecurityToolingAccountId: ""
      Section1ToolingAndLoggingRegion: "us-east-1"
      Section1LogArchivingAccountId: ""
      Section1OrganizationRootID: ""
      Section1DeliveryBucketPrefix: logs-delivery
      Section1SumoLogicResourceRemoveOnDeleteStack: "true"

      Section2InstallSumoGlobalGuardDutyApp: "Yes"
      Section2InstallSumoCloudSecurityMonitoringandAnalyticsGuardDutyApp: "Yes"
      Section2GuardDutyRegions: "us-east-1"
      Section2AdditionalConfigurationFeatures: "MalwareProtection,S3Logs"
      Section2GuardDutyCreateHttpLogsSource: "Yes"
      Section2GuardDutyHttpLogsSourceCategoryName: "aws/quickstart/guardduty/logs"

      Section3CloudTrailRegion: "us-east-1"
      Section3EnableAWSCloudTrail: "Yes"
      # Section3CloudTrailExistsS3BucketName: "" not required if Section3CreateCloudTrailS3Bucket: "Yes"
      Section3InstallPCICloudTrailApp: "Yes"
      Section3InstallCISFoundationApp: "Yes"
      Section3InstallCloudTrailMonitoringAnalyticsApp: "Yes"
      Section3InstallCloudTrailSecOpsApp: "Yes"
      Section3CloudTrailCreateS3LogsSource: "Yes"
      Section3CreateCloudTrailS3Bucket: "Yes"
      Section3DisassociateAdminAccountOnDeleteStack: "false"
      Section3CloudTrailLogsSourceCategoryName: "aws/quickstart/cloudtrail/logs"
      Section3CloudTrailBucketPathExpression: "CloudTrail/AWSLogs/*"
      
      Section4SecurityHubEnableSecurityHub: "Yes"
      Section4SecurityHubAggregationRegion: "us-east-1"
      Section4SecurityHubRegionLinkingMode: "SPECIFIED_REGIONS"
      Section4SecurityHubLinkedRegions: "us-east-2"
      Section4SecurityHubInstallSumoSecurityHubCloudSecurityMonitoringandAnalyticsApp: "Yes"
      Section4SecurityHubCreateHttpLogsSource: "Yes"
      Section4SecurityHubHttpLogsSourceCategoryName: "aws/quickstart/securityhub/logs"
      Section4SecurityHubSecurityStandards: "FSBP_v1.0.0,CIS_v1.2.0,PCI_DSS_v3.2.1,NIST_v5.0.0,CIS_v1.4.0"

      Section6EnableFirewallManager: "Yes"
      Section6DisassociateAdminAccountOnDeleteStack: "false"
      Section6InstallSumoAWSWAFCloudSecurityMonitoringAndAnalyticsApp: "Yes"
      Section6InstallSumoAWSNetworkFirewallApp: "Yes"
      Section6FirewallManagerPolicyRegions: "us-east-1"
      Section6CreateDeliveryStreamSource: "Yes"
      Section6DeliveryStreamName: sumologic-kinesis-$[taskcat_random-string]
      Section6CreateS3Source: "Yes"
      Section6CreateS3Bucket: "Yes"
      Section6DeliveryBucketPrefix: nw-logs-delivery
      Section6S3SourceCategoryName: "aws/quickstart/nfw/logs"
      Section6DeliveryStreamSourceCategoryName: "aws/quickstart/waf/logs"
      Section6CreateVpcForSG: "true"
      
