AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: This solution consists of a lambda function which which gets triggered by CloudWatch events with findings as payload which are then ingested to Sumo Logic via S3 source. (qs-1urq28kag)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: SumoLogic Attributes
        Parameters:
          - SumoEndpoint
    ParameterLabels:
      SumoEndpoint:
        default: SumoLogic Endpoint to post logs
Parameters:
  SumoEndpoint:
    Description: "SumoLogic Endpoint to post logs"
    Type: "String" 

Resources:

  SecurityHubForwarder:
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-securityhub-forwarder
        SemanticVersion: 1.0.10
        
  SecurityHubUserKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: SecurityHubUser

  IamGroupReadonly:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/ReadOnlyAccess"
      Policies:
        - PolicyName: apigatewayaccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: execute-api:Invoke
                Resource: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/findings"
                    
  SecurityHubUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join
        - ""
        - - "SecurityHubUser-"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split ["/", !Ref "AWS::StackId"]
      Groups:
      - !Ref 'IamGroupReadonly'

  SecurityHubConnectorAwsOrg:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-securityhub-connector-aws-org
        SemanticVersion: 1.0.5
      Parameters: 
        SumoEndpoint: !Ref SumoEndpoint  
      
Outputs:

  oSecurityHubSecretAccessKey:
    Description: Security Hub Secret Access Key
    Value: !GetAtt SecurityHubUserKey.SecretAccessKey   

  oSecurityHubUserKey:
    Description: Access Key of User
    Value: !Ref SecurityHubUserKey

  oSecurityHubForwarderApiUrl:
    Description: Security Hub Forwarder Api Url
    Value: !GetAtt SecurityHubForwarder.Outputs.SecurityHubForwarderApiUrl    
