########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: Create an IAM role to disassociate the administrator account (qs-1urq10qd6)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: Role Attributes
        Parameters:
          - FMSDisassociateRoleName
          - OrgManagementAccountId
          - OrgManagementLambdaRoleName
    ParameterLabels:
      FMSDisassociateRoleName:
        default: FMS Disassociate IAM Role Name
      OrgManagementAccountId:
        default: Organization Management Account ID
      OrgManagementLambdaRoleName: 
        default: Organization Management Lambda Role Name

Parameters:
  FMSDisassociateRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: FMS IAM Role Name
    Type: String

  OrgManagementAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization management account ID
    Type: String

  OrgManagementLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: Organization Management Account Lambda Role Name
    Type: String

Resources:
  FMSDisassociateRole: 
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Allow put and delete configuration aggregator for all aggregators
          - id: W28
            reason: Explicit name provided for automation resource identification
    Properties:
      RoleName: !Ref FMSDisassociateRoleName
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn:
                  - !Sub arn:${AWS::Partition}:iam::${OrgManagementAccountId}:role/${OrgManagementLambdaRoleName}
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${OrgManagementAccountId}:root

      Path: "/"
      Policies: 
        - PolicyName: !Ref FMSDisassociateRoleName
          PolicyDocument:
            Version: 2012-10-17
            Statement:         
              - Action:
                  - fms:DisassociateAdminAccount
                  - fms:GetAdminAccount
                Effect: Allow
                Resource: "*"
                Sid: AllowFMSDisassociateAdminAccount

              - Action:
                  - organizations:DescribeOrganization
                  - organizations:ListAccounts
                Effect: Allow
                Resource: "*"
                Sid: OrganizationAccess

              - Action:
                  - organizations:DescribeAccount
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:organizations::*:account/*/*
                Sid: OrganizationDescribeAccount